title: Yoshiteru Nagata
logo: "/assets/img/profile.jpg?raw=true"
jdlae: "/assets/img/engineer2022_1_regular.png?raw=true"
description: 永田 吉輝
affiliation: >
  Doctoral student in <a href="https://www.ucl.nuee.nagoya-u.ac.jp/en/" target="_blank">Kawaguchi Lab.</a>, <a href="https://www.nuee.nagoya-u.ac.jp/index-e.php" target="_blank">Dept. of Information and Communication Eng., Grad. School of Eng., Nagoya University.</a><br>
  CEO, <a href="https://exdata.co.jp/" target="_blank">ExData, Inc.</a>
links: >
  <a href="https://www.ucl.nuee.nagoya-u.ac.jp/en/" target="_blank">UCLab (Kawaguchi Lab.)</a><br>
  <a href="https://exdata.co.jp/" target="_blank">ExData, Inc.</a><br>
  <a href="https://media.itc.nagoya-u.ac.jp/studio/" target="_blank">Media Studio</a><br>
  <a href="https://tarvo.co.jp/" target="_blank">TARVO, Inc.</a><br>
affiliation-ja: >
  <a href="https://www.nuee.nagoya-u.ac.jp/" target="_blank">名古屋大学大学院工学研究科情報・通信工学専攻</a> <a href="https://www.ucl.nuee.nagoya-u.ac.jp/" target="_blank">河口研究室</a> 博士後期課程<br>
  <a href="https://exdata.co.jp/" target="_blank">株式会社ExData</a> 代表取締役
links-ja: >
  <a href="https://www.ucl.nuee.nagoya-u.ac.jp/" target="_blank">UCLab (河口研究室)</a><br>
  <a href="https://exdata.co.jp/" target="_blank">株式会社ExData</a><br>
  <a href="https://media.itc.nagoya-u.ac.jp/studio/" target="_blank">情報メディアスタジオ</a><br>
  <a href="https://tarvo.co.jp/" target="_blank">株式会社TARVO</a><br>
theme: jekyll-theme-minimal
google_analytics: G-P72C9J4MEN
show_downloads: false
researchmap_url: "https://researchmap.jp/uclteru"
researchmap_url_en: "https://researchmap.jp/uclteru?lang=en"
x_url: "https://x.com/80301y"
instagram_url: "https://www.instagram.com/ucl_teru/"
